### ISSUE TITLE
GitHub warns about Node.js 16 actions being deprecated

### ISSUE THREAD

**Issue by ashaduri** [nerdoza/action-simple-file-upload#23]
Got this message today:

`Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: bayssmekanique/action-simple-file-upload@v2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.`

Thanks!

**Comment by nerdoza** [comment]
Resolved by 9b622b90e28b8170b2c86de4046d29f4065bfa49.

Update to `v2.2.0` if you are using pinned versions, otherwise the fix should come through with the updated `v2` tag.
